apiVersion: v1
kind: Service
metadata:
 labels:
   app: minecraft
 name: minecraft
 namespace: default
spec:
 clusterIP: 10.0.118.230
 externalTrafficPolicy: Cluster
 ports:
 - name: 25565-25565
   nodePort: 31050
   port: 25565
   protocol: TCP
   targetPort: 25565
 - name: rcon
   nodePort: 31051
   port: 25575
   protocol: TCP
   targetPort: 25575
 selector:
   app: minecraft
 sessionAffinity: None
 type: LoadBalancer
status:
 loadBalancer: {}